name: brndnmtthws/rust-action
description: |
  All-in-one Rust action for linting, building, testing, and producing coverage
  reports.
author: Brenden Matthews <github@brenden.brndn.io>
branding:
  icon: box
  color: purple

inputs:
  toolchain:
    default: stable
    description: Specify a Rust toolchain.
  components:
    default: |
      clippy
      rustfmt
    description: Rust components to install along with the toolchain.
  cargo-packages:
    default: |
      cargo-tarpaulin
    description: The default set of cargo packages to install
  disable-cargo-registry-cache:
    description: If set to 'true', the Cargo registry cache will not be enabled.
  disable-cargo-target-cache:
    description: If set to 'true', the Cargo target cache will not be enabled.
  enable-sccache:
    description: If set to 'true', sccache will be enabled.
  cargo-registry-cache-key:
    default: |
      cargo-registry-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
    description: The Cargo registry cache key.
  cargo-registry-cache-restore-keys:
    default: |
      cargo-registry-${{ runner.os }}-${{ runner.arch }}-
      cargo-registry-${{ runner.os }}-
      cargo-registry-
    description: The Cargo registry cache restoration keys.
  cargo-target-cache-key:
    default: |
      cargo-target-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
    description: The Cargo target cache key.
  cargo-target-cache-restore-keys:
    default: |
      cargo-target-${{ runner.os }}-${{ runner.arch }}-
      cargo-target-${{ runner.os }}-
      cargo-target-
    description: The Cargo target cache restoration keys.
  cargo-target-cache-path:
    default: '**/target/*'
    description: |
      The path glob for the Cargo target dir.
  sccache-cache-key:
    default: |
      sccache-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
    description: The sccache local file cache key.
  sccache-cache-restore-keys:
    default: |
      sccache-${{ runner.os }}-${{ runner.arch }}-
      sccache-${{ runner.os }}-
      sccache-
    description: The sccache local file cache restoration keys.

runs:
  using: 'composite'
  steps:
    - uses: brndnmtthws/rust-action-rustup@v1
      name: Install toolchain
      with:
        toolchain: ${{ inputs.toolchain }}
        profile: minimal
        components: |
          rustfmt
          clippy
    - uses: actions/cache@v3
      name: Cache Cargo registry
      if: ${{ inputs.disable-cargo-registry-cache != 'true' }}
      with:
        key: ${{ inputs.cargo-registry-cache-key }}
        restore-keys: ${{ inputs.cargo-registry-cache-restore-keys }}
        path: |
          ~/.cargo/registry
    - uses: actions/cache@v3
      name: Cache Cargo target
      if: ${{ inputs.disable-cargo-target-cache != 'true' }}
      with:
        key: ${{ inputs.cargo-target-cache-key }}
        restore-keys: ${{ inputs.cargo-target-cache-restore-keys }}
        path: ${{ inputs.cargo-target-cache-path }}
    - uses: actions/cache@v3
      name: Cache sccache local files
      if: ${{ inputs.enable-sccache == 'true' }}
      with:
        key: ${{ inputs.sccache-cache-key }}
        restore-keys: ${{ inputs.sccache-cache-restore-keys }}
        path: |
          ~/.sccache
    - shell: bash
      run: echo "SCCACHE_DIR=$HOME/.sccache" >> $GITHUB_ENV
      if: ${{ inputs.enable-sccache == 'true' }}
    - shell: bash
      run: echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      if: ${{ inputs.enable-sccache == 'true' }}
    - shell: bash
      run: echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
      if: ${{ inputs.enable-sccache == 'true' }}
    - uses: brndnmtthws/rust-action-cargo-binstall@v1
      name: Install Cargo packages
      with:
        packages: ${{ inputs.cargo-packages }}
    - uses: brndnmtthws/rust-action-cargo-binstall@v1
      name: Install sccache
      if: ${{ inputs.enable-sccache == 'true' }}
      with:
        packages: sccache
